CREATE TABLE "games" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "release_year" date,
  "description" varchar(255),
  "image_file" varchar(100),
  "developer_id" integer,
  "publisher_id" integer
);

CREATE TABLE "developers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "founded_year" date,
  "country" varchar(100),
  "info" varchar(255),
  "image_file" varchar(100)
);

CREATE TABLE "publishers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "founded_year" date,
  "country" varchar(100),
  "info" varchar(255),
  "image_file" varchar(100)
);

CREATE TABLE "genres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "platforms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100)
);

CREATE TABLE "games_genres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" integer NOT NULL,
  "genre_id" integer NOT NULL
);

CREATE TABLE "games_platforms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" integer NOT NULL,
  "platform_id" integer NOT NULL
);

ALTER TABLE "games" ADD CONSTRAINT "game_developer" FOREIGN KEY ("developer_id") REFERENCES "developers" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "games" ADD CONSTRAINT "game_publisher" FOREIGN KEY ("publisher_id") REFERENCES "publishers" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "games_genres" ADD CONSTRAINT "game_genre_game_id" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "games_genres" ADD CONSTRAINT "game_genre_genre_id" FOREIGN KEY ("genre_id") REFERENCES "genres" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "games_platforms" ADD CONSTRAINT "game_platform_game_id" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "games_platforms" ADD CONSTRAINT "game_platform_platform_id" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
